dist: xenial
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  on:
    tags: true
  skip_existing: true
  user: mosorio
  password:
    secure: TgsmUWVgjKGTBWsTjH3p4F0h/n41VUf0xkQvhM+jstEIdz79WufwpdRYfPEghtnVZnfSd81WbiqOcs9Ks8Vzs9s/X+vXpqYU6ktEYddnv8cYA+1e4Uv6qc7ZSPbNuS5SpR9l+zhXmHZZfAWkQQG5hn1vKyEq55MtXOvcqvHkdvcW9OCQFG3+6IDU4wA3DgSnZeVdPQoE6GDjoiAyL2yku3UIaVdHnMkLDKKGRXFo4021X1+4RpYKKBtPQZukUa0nl8s23db3J9NLxup6GzGaPP3csYgkZ1xf8ha2SctKXKzUSwykPof+0g1R1WWyU4z4NXoZtG/pLBq4n9aGeFlsBuHC7/zK3NvUjuG6IPm2NlADQpbkhfmKeuCzVQ++yCBIVUF/8vGV3DwF7wPnPqIIrbS37iq0czMoaxc/5eQWu2RGKcvHub0w97rAB8VMrgZS6/QDonNZLdaPeZkJCMq0kQb8u9T+3XWGVeSwFFI1Fj0EZTfhN6S28J+pxOyd9r7toqQt2GVyD8z0SefkW2LlFnmI8dFtOMIW29kaw4FOUFnP7iofH64ZfkIGqJ4wPNr1LNLnRG7KP/5TgR1G9sFLxrxo4LICD5ZCHXCRQCzD86R5JYk3NdDfa6P49bVr+ALycvjHjzvO69dzH2aaNtePahT8yjNJDnNzvM3sFJ/lODE=
