language: python
services:
  - docker
matrix:
  include:
  - os: linux
    python: '3.6'
  - os: linux
    python: '3.7'
  - os: linux
    python: '3.8'
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - pip install -U pip
  - pip install -r test-requirements.txt
  - pip install --upgrade setuptools wheel
  - python setup.py install
script:
 - pytest
after_success:
- codecov
deploy:
  provider: pypi
  on:
    tags: true
  skip_existing: true
  user: "__token__"
  password:
    secure: AimmtfI+bZ6AZpGXb92TKqj8+0p1htPILJRgeoU6Mrq1pXoxYZBFGire88kRM7KmuWPh3bRZ2eAimtFxXLypDrBqtwtA1VzdqTVe60UHF9gm6MrXz9Rz3b7IKv15bX6l4mx6z1O9u8AJT5Xs+Uu+QSy6uOTRqwiDOQ9m0ijv4Q7auFwvekQv6kRfUExqSLw19cO97VAzvfE03PBzxgopZ6fo3jA7fJg2Nt2dwszj41iU86vnXZafIpmfqDGV4PvDeSZW2+c08W34U9bZWZGvu0ss1b1TYzJ6L/K426T1caR8y65TJgn3FYvqIrkwnwBdObKLayILZ1dmpfLolx3c3VKrxFtTe7Njat7khqsvOdeIrOo83BfU4VAFCuvzzAMzAvXQS7DsoQ3MIpazOT3adyyWluyZjw7KGdWeYLkrNCb0xMpBSnskh9UeluwhtC96f4iF69hfHLrEOxV/GhAySNz7kkNnd37A8QEJ5cEwS27aB7Is4l2+a/HgzINS56+ECe6Nm8QZhYNb1rBwtu50kb9ak3GL2yHU6Y0eH+eHaLN3IzBGcgQr1YsREkh1KBAnCS4TMg7Q2x0da8GrQDNi4WSUrpZFx4bT6i3wWkeU6Px/UgaJ6PqHKGxOLwUVBuDle0zzS0G6BcvVlOSYPoboEK9E2VmanB1xw+/HhEPOjqg=
