#+ summary: Return the query to a resource by the resource_iri
CONSTRUCT {
 ?_resource_iri ?predicate ?prop .
 ?prop a ?type .
 ?prop rdfs:label ?label 
}
WHERE {

?_resource_iri ?predicate ?prop 
{
?item ?predicate ?prop
}
OPTIONAL {
?prop rdfs:label ?label ;
      a ?type
}
}
